### ISSUE TITLE
[Bug] Vanilla grindstone is unusable

### ISSUE THREAD

**Issue by SplendidAlakey** [xanthian/variantgrindstones#1]
* Version of Variant Grindstones 1.0.7
* Version of Fabric API 0.61.0
* Version of Minecraft 1.19.2
* Version of Fabric Loader 0.14.9
* Mod List none
* Screen shot or logs of any errors https://gist.github.com/Footage2-Amply-Pounce/75c6edf57a087fe49ef42e091f2ab4f3

Structure mods always use vanilla grindstones, so it's a bit problematic finding useless grindstones.

**Comment by xanthian** [comment]
unusable how?
nothing in log to show anything.

**Comment by SplendidAlakey** [comment]
You can't interact with it. When you right-click on it, the GUI automatically closes so fast, it sometimes has no time to even render.

Edit: also noticed that in logs it says I gave myself a dark oak grindstone, but I specifically gave myself the vanilla `minecraft:grindstone` one.

**Comment by xanthian** [comment]
vanilla was renamed to dark oak as the texture is identical.
i've replicated the issue, seems its only the vanilla block but the modded ones are ok.
will work on it today

**Comment by xanthian** [comment]
issue found, 1.0.8 will be on CF shortly.
apologies. 
https://github.com/xanthian/variantgrindstones/commit/7c8c90db24dd986d6fb31d6d5adc953abfadd16b
