### ISSUE TITLE
[Bug] Villagers do not see modded grindstones as workstations. Only vanilla minecraft:grindstone.

### ISSUE THREAD

**Issue by Mnky313** [xanthian/variantgrindstones#2]
Villagers do not see modded grindstones as workstations. Only vanilla minecraft:grindstone.

Variant Grindstones: 1.0.9
Fabric API: 0.59.0+1.19.2
Minecraft: 1.19.2
Fabric Loader: 0.14.9
Tested with just VariantGrindstones

**Comment by xanthian** [comment]
Not a bug as such, waiting for bclib to add functionality.

**Comment by xanthian** [comment]
Actually, scrap that, 1.10 will have POI functionality!
You'll need to break and replace your existing Grindstones.
